import '../scss/style.scss'
import '../js/about-company'
import '../js/slider-brand.js'
import '../js/slider-technic.js'
import '../js/slider-price.js'
import '../js/popup.js'
import '../js/aside-items'
